version: '2'
services:
  reverse_proxy:
    build:
      context: src/are-you-lost-ionic/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - lostnet
  flaskserv:
    build:
      context: src/flaskserv/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - lostnet

networks:
  lostnet:
