version: '2'
services:
  reverse_proxy:
    build:
      context: src/are-you-lost-ionic/
      dockerfile: Dockerfile
    ports:
      - 8100:8100
    networks:
      - lostnet
  flaskserv:
    build:
      context: src/flaskserv/
      dockerfile: Dockerfile
    expose:
      - 5000
    networks:
      - lostnet

networks:
  lostnet:
